apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-webserver-configures
data:
  web.yaml: |-
    #elasticsearch相关
    es:
      # 全文检索功能开关(取值：off/on)，默认是off，开启是on
      fullTextSearch: {{ .Values.web.es.fullTextSearch | quote }}
    # web_server专属配置
    webServer:
      api:
        version:  v3
      #会话相关
      session:
        #会话名
        name: {{ .Values.web.webServer.session.name }}
        skip: "0"
        #是否支持同时登录同一用户，0为不支持，1为支持
        multipleOwner: {{ .Values.web.webServer.session.multipleOwner }}
        #账号密码，以 : 分割
        userInfo: {{ .Values.web.webServer.session.userInfo }}
      site:
        #该值表示部署完成后,输入到浏览器中访问的cmdb 网址
        domainUrl: {{ .Values.web.webServer.site.domainUrl }}
        httpsDomainUrl: {{ .Values.web.webServer.site.httpsDomainUrl }}
        #登录地址
        bkLoginUrl: {{ include "cmdb.webserver.bkLoginUrl" . }}
        bkHttpsLoginUrl: {{ include "cmdb.webserver.bkHttpsLoginUrl" . }}
        appCode: {{ .Values.web.webServer.site.appCode }}
        resourcesPath: {{ .Values.web.webServer.site.resourcesPath }}
        #前端基础页面位置
        htmlRoot: {{ .Values.web.webServer.site.htmlRoot }}
        authscheme: {{ .Values.web.webServer.site.authScheme }}
        bkComponentApiUrl:  {{ include "cmdb.webserver.bkComponentApiUrl" . }}
        paasDomainUrl: {{ include "cmdb.webserver.paas_domain_url" . }}
        # bkDomain 用于配置前端需要的cookie domain地址
        bkDomain: {{ .Values.web.webServer.site.bkDomain }}
        #帮助文档地址
        helpDocUrl: {{ .Values.web.webServer.site.helpDocUrl }}
        # 蓝鲸共享资源URL
        bkSharedResUrl: {{ .Values.bkSharedResUrl }}
        # 网关API访问地址模板
        bkApiUrlTmpl: {{ .Values.bkApiUrlTmpl }}
        paas:
          # pass的tls相关配置
          tls:
            # 客户端是否验证服务端证书，包含证书链和主机名，bool值, true为不校验, false为校验
            insecureSkipVerify: {{ .Values.web.paas.tls.insecureSkipVerify }}
            # 服务使用的证书的路径,如:/data/cmdb/cert/server.crt
            certFile: {{ .Values.web.paas.tls.certFile }}
            # 服务使用的证书对应的密钥的路径,如:/data/cmdb/cert/server.key
            keyFile: {{ .Values.web.paas.tls.keyFile }}
            # CA证书的路径，用于验证对方证书,如:/data/cmdb/cert/ca.crt
            caFile: {{ .Values.web.paas.tls.caFile }}
            # 用于解密根据RFC1423加密的证书密钥的PEM块
            password: {{ .Values.web.paas.tls.password }}
      app:
        agentAppUrl: {{ .Values.bkNodemanUrl }}
        #权限模式，web页面使用，可选值: internal, iam
        authscheme: {{ .Values.web.webServer.app.authScheme }}
      login:
        # 使用的登录系统， skip-login 免登陆模式， blueking 默认登录模式， 使用蓝鲸登录, oa 使用公司oa进行登陆
        version: {{ .Values.web.webServer.login.version }}
      #cmdb版本日志存放路径配置
      changelogPath:
        #中文版版本日志存放路径
        ch: {{ .Values.web.webServer.changelogPath.ch }}
        #英文版版本日志存放路径
        en: {{ .Values.web.webServer.changelogPath.en }}
      # web-server使用的jwt配置
      jwt:
        # 是否开启jwt认证功能
        enabled: {{ .Values.web.webServer.jwt.enabled }}
        # jwt公钥
        publicKey: {{ .Values.web.webServer.jwt.publicKey }}
        # jwt私钥
        privateKey:  {{ .Values.web.webServer.jwt.privateKey }}
      #是否启用消息通知
      enableNotification: {{ .Values.web.webServer.enableNotification }}

    # cmdb服务tls配置
    tls:
      # 客户端是否验证服务端证书，包含证书链和主机名，bool值, true为不校验, false为校验
      insecureSkipVerify: {{ .Values.web.tls.insecureSkipVerify }}
      # 服务使用的证书的路径,如:/data/cmdb/cert/server.crt
      certFile: {{ .Values.web.tls.certFile }}
      # 服务使用的证书对应的密钥的路径,如:/data/cmdb/cert/server.key
      keyFile: {{ .Values.web.tls.keyFile }}
      # CA证书的路径，用于验证对方证书,,如:/data/cmdb/cert/ca.crt
      caFile: {{ .Values.web.tls.caFile }}
      # 用于解密根据RFC1423加密的证书密钥的PEM块
      password: {{ .Values.web.tls.password }}

    # 调用apigw接口相关配置
    apiGW:
      bkGseApiGatewayUrl: {{ .Values.bkGseApiGatewayUrl }}
      bkNoticeApiGatewayUrl: {{ .Values.bkNoticeApiGatewayUrl }}
      bkCmdbApiGatewayUrl: {{ .Values.bkCmdbApiGatewayUrl }}
      bkLoginApiGatewayUrl: {{ .Values.bkLoginApiGatewayUrl }}
      appCode: {{ .Values.web.apiGW.appCode }}
      appSecret: {{ .Values.web.apiGW.appSecret }}
      username: {{ .Values.web.apiGW.username }}
      tls:
        # 客户端是否验证服务端证书，包含证书链和主机名，bool值, true为不校验, false为校验
        insecureSkipVerify: {{ .Values.web.apiGW.tls.insecureSkipVerify }}
        # 服务使用的证书的路径,如:/data/cmdb/cert/server.crt
        certFile: {{ .Values.web.apiGW.tls.certFile }}
        # 服务使用的证书对应的密钥的路径,如:/data/cmdb/cert/server.key
        keyFile: {{ .Values.web.apiGW.tls.keyFile }}
        # CA证书的路径，用于验证对方证书,如:/data/cmdb/cert/ca.crt
        caFile: {{ .Values.web.apiGW.tls.caFile }}
        # 用于解密根据RFC1423加密的证书密钥的PEM块
        password: {{ .Values.web.apiGW.tls.password }}

    # 监控配置， monitor配置项必须存在
    monitor:
      # 监控插件名称，有noop，blueking， 不填时默认为noop
      pluginName: {{ .Values.web.monitor.pluginName }}
      # 是否开启监控
      enableMonitor: {{ .Values.web.monitor.enabled }}
      # 当使用blueking监控插件时，上报数据所需要的数据通道标识,如1500000
      dataID: {{ .Values.web.monitor.dataId }}
      # 采集数据后能够缓存的队列长度，设置范围为1～1000, 默认为100
      queueSize: {{ .Values.web.monitor.queueSize }}
      # 采集数据用的gsecmdline命令绝对路径，默认版本需要大于等于2.0.2 ，默认路径：/usr/local/gse/plugins/bin/gsecmdline
      gsecmdlinePath: {{ .Values.web.monitor.gsecmdlinePath }}
      # 对应的domainsocket绝对路径，默认路径：/usr/local/gse/agent/data/ipc.state.report
      domainSocketPath: {{ .Values.web.monitor.domainSocketPath }}
      # 用于对数据上报进行频率控制和限流
      # qps的设置范围为1～50，默认值为10
      # burst的设置范围为1～100，默认值为20
      rateLimiter:
        qps: {{ .Values.web.monitor.rateLimiter.qps }}
        burst: {{ .Values.web.monitor.rateLimiter.burst }}

    # openTelemetry跟踪链接入相关配置
    openTelemetry:
      # 表示是否开启openTelemetry跟踪链接入相关功能，布尔值, 默认值为false不开启
      enable: {{ .Values.web.openTelemetry.enable }}
      # openTelemetry跟踪链功能的自定义上报服务地址
      endpoint: {{ .Values.web.openTelemetry.endpoint }}
      # openTelemetry跟踪链功能的上报data_id, 用于旧版的数据上报, 和bkDataToken同时配置时，会取bkDataToken
      bkDataID: {{ .Values.web.openTelemetry.bkDataID }}
      # openTelemetry跟踪链功能的bk.data.token, 用于新版的数据上报，和bkDataID同时配置时，会取bkDataToken
      bkDataToken: {{ .Values.web.openTelemetry.bkDataToken }}
      # 连接日志平台tls配置
      tls:
        # 客户端是否验证服务端证书，包含证书链和主机名，bool值, true为不校验, false为校验
        insecureSkipVerify: {{ .Values.web.openTelemetry.tls.insecureSkipVerify }}
        # 服务使用的证书的路径,如:/data/cmdb/cert/server.crt
        certFile: {{ .Values.web.openTelemetry.tls.certFile }}
        # 服务使用的证书对应的密钥的路径,如:/data/cmdb/cert/server.key
        keyFile: {{ .Values.web.openTelemetry.tls.keyFile }}
        # CA证书的路径，用于验证对方证书,如:/data/cmdb/cert/ca.crt
        caFile: {{ .Values.web.openTelemetry.tls.caFile }}
        # 用于解密根据RFC1423加密的证书密钥的PEM块
        password: {{ .Values.web.openTelemetry.tls.password }}

    errors:
      res: {{ .Values.webserver.errors }}

    language:
      res: {{ .Values.webserver.language }}

    mongodb:
      host: {{ include "cmdb.mongodb.addr" . | quote }}
      usr: {{ include "cmdb.mongodb.usr" . | quote }}
      pwd: {{ include "cmdb.mongodb.pwd" . | quote }}
      database: {{ .Values.mongodb.externalMongodb.database }}
      maxOpenConns: {{ .Values.mongodb.externalMongodb.maxOpenConns }}
      maxIdleConns: {{ .Values.mongodb.externalMongodb.maxIdleConns }}

      mechanism: {{ .Values.mongodb.externalMongodb.mechanism }}
      rsName: {{ .Values.mongodb.externalMongodb.rsName }}
      #mongo的socket连接的超时时间，以秒为单位，默认10s，最小5s，最大30s。
      socketTimeoutSeconds: {{ .Values.mongodb.externalMongodb.socketTimeoutSeconds }}
      enable: {{ .Values.mongodb.externalMongodb.enabled }}

    redis:
      host: {{ include "cmdb.redis.host" . | quote }}
      pwd: {{ include "cmdb.redis.pwd" . | quote }}
      database: {{ .Values.redis.redis.database }}
      maxOpenConns: {{ .Values.redis.redis.maxOpenConns }}
      maxIdleConns: {{ .Values.redis.redis.maxIdleConns }}
      sentinelPwd: {{ .Values.redis.redis.sentinelPwd }}
      masterName: {{ .Values.redis.redis.masterName }}