apiVersion: v2
appVersion: 3.11.4-alpha1
description: BlueKing Configuration Management DataBase (bk-cmdb) is an enterprise level configuration management serivce database.
name: bk-cmdb
type: application
version: 3.12.4-alpha1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.2.2
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.17
  - condition: mongodb.enabled
    name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 13.6.1
  - condition: elasticsearch.enabled
    name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 19.5.5
  - condition: zookeeper.enabled
    name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 11.0.2
