{{- if .Values.procserver.enabled }}
apiVersion: {{ .Values.ApiVersion.Deployment }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-procserver"
  labels:
    {{- include "bk-cmdb.labels" . | nindent 4 }}
    component: procserver
spec:
  replicas: {{ .Values.procserver.replicas }}
  selector:
    matchLabels:
      {{- include "bk-cmdb.matchLabels" . | nindent 6 }}
      component: procserver
  template:
    metadata:
      labels:
        {{- include "bk-cmdb.labels" . | nindent 8 }}
        component: procserver
        values-hash: "{{ toYaml .Values | sha256sum | trunc 63 }}"
      {{- with .Values.procserver.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.procserver.podAnnotations }}
        {{ toYaml .Values.procserver.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: procserver
        image: {{ .Values.image.registry }}/{{ .Values.procserver.image.repository }}:{{ .Values.procserver.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        workingDir: {{ .Values.procserver.workDir }}
        command:
        - ./cmdb_procserver
        - --addrport=$(POD_IP):{{ .Values.procserver.port }}
        {{- if .Values.procserver.configDir }}
        - --config={{ .Values.procserver.configDir }}
        {{- end }}
        - --regdiscv={{ include "cmdb.configAndServiceCenter.addr" . }}
        {{- if .Values.procserver.command.logDir }}
        - --log-dir={{ .Values.procserver.command.logDir }}
        {{- end }}
        - --v={{ .Values.procserver.command.logLevel }}
        - --logtostderr={{ .Values.procserver.command.logtostderr }}
        - "--enable-auth"
        - {{ .Values.cmdb.auth.enable | quote }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.procserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.procserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10

        {{- if .Values.procserver.resources }}
        resources:
          {{ toYaml .Values.procserver.resources | indent 10 }}
        {{- end }}

        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        {{- if .Values.procserver.env }}
          {{ toYaml .Values.procserver.env | indent 10 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.procserver.port }}

      {{- if .Values.procserver.configDir }}
        volumeMounts:
          - name: configures
            mountPath: {{ .Values.procserver.configDir }}
      volumes:
        - name: configures
          configMap:
            name: {{ .Release.Name }}-procserver-configures
      {{- end }}

      {{- with .Values.procserver.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.procserver.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.procserver.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

{{- end }}
