# 指定errors的路径
errors:
  res: __BK_HOME__/cmdb/errors
# 指定language的路径
language:
  res: __BK_HOME__/cmdb/language
#elasticsearch配置
es:
  #全文检索功能开关(取值：off/on)，默认是off，开启是on
  fullTextSearch: "off"
# web_server专属配置
webServer:
  api:
    host: __BK_CMDB_API_HOST__
    port: __BK_CMDB_API_PORT__
    #显示版本，比如v3为3.x
    version: v3
  #会话相关
  session:
    #会话名
    name: cc3
    skip: "0"
    #是否支持同时登录同一用户，0为不支持，1为支持
    multipleOwner: "0"
    #登陆方式为opensource时的用户密码，用户和密码以:分割，多个账户以逗号分割，如user1:password1,user2:password2
    userInfo:
  site:
    #该值表示部署完成后,输入到浏览器中访问的cmdb 网址
    domainUrl: __BK_CMDB_PUBLIC_URL__
    httpsDomainUrl: __BK_CMDB_PUBLIC_URL__
    #登录地址
    bkLoginUrl: http://__BK_PAAS_PUBLIC_ADDR__/login/?app_id=%s&c_url=%s
    bkHttpsLoginUrl: https://__BK_PAAS_PUBLIC_ADDR__/login/?app_id=%s&c_url=%s
    appCode: __BK_CMDB_APP_CODE__
    checkUrl: http://__BK_PAAS_PRIVATE_ADDR__/login/accounts/get_user/?bk_token=
    resourcesPath: /tmp/
    #前端基础页面位置
    htmlRoot: __BK_HOME__/cmdb/web/
    authscheme: iam
    # 蓝鲸 ESB url
    bkComponentApiUrl:  http://bkapi.__BK_PAAS_PUBLIC_ADDR__
    # paas的地址，给前端的人员选择器使用
    paasDomainUrl: http://__BK_PAAS_PRIVATE_ADDR__
    # bkDomain 用于配置前端需要的cookie domain地址
    bkDomain: .__BK_DOMAIN__
    #帮助文档地址
    helpDocUrl: __BK_HTTP_SCHEMA__://__BK_PAAS_PUBLIC_ADDR__/o/bk_docs_center/markdown/配置平台/产品白皮书/产品简介/Overview.md
    paas:
      # pass的tls相关配置
      tls:
        # 客户端是否验证服务端证书，包含证书链和主机名，bool值, true为不校验, false为校验
        insecureSkipVerify: true
        # 服务使用的证书的路径,如:/data/cmdb/cert/server.crt
        certFile:
        # 服务使用的证书对应的密钥的路径,如:/data/cmdb/cert/server.key
        keyFile:
        # CA证书的路径，用于验证对方证书,如:/data/cmdb/cert/ca.crt
        caFile:
        # 用于解密根据RFC1423加密的证书密钥的PEM块
        password:
  app:
    #蓝鲸权限中心的应用编码
    authAppCode: bk_iam
    # 权限中心地址
    authUrl: __BK_HTTP_SCHEMA__://__BK_PAAS_PUBLIC_ADDR__/o/bk_iam/apply-custom-perm
    # 用来配置节点管理平台的url
    agentAppUrl: __BK_HTTP_SCHEMA__://__BK_PAAS_PUBLIC_ADDR__/o/bk_nodeman/
    #权限模式，web页面使用，可选值: internal, iam
    authscheme: iam
  login:
    # 使用的登录系统， skip-login 免登陆模式， blueking 默认登录模式， 使用蓝鲸登录
    version: blueking
  #cmdb版本日志存放路径配置
  changelogPath:
    #中文版版本日志存放路径
    ch: __BK_HOME__/cmdb/server/changelog_user/ch
    #英文版版本日志存放路径
    en: __BK_HOME__/cmdb/server/changelog_user/en
  # web-server使用的jwt配置
  jwt:
    # 是否开启jwt认证功能
    enabled: false
    # jwt公钥
    publicKey:
    # jwt私钥
    privateKey:
  #是否启用消息通知
  enableNotification: __BK_NOTICE_ENABLED__

# cmdb服务tls配置
tls:
  # 客户端是否验证服务端证书，包含证书链和主机名，bool值, true为不校验, false为校验
  insecureSkipVerify: true
  # 服务使用的证书的路径,如:/data/cmdb/cert/server.crt
  certFile:
  # 服务使用的证书对应的密钥的路径,如:/data/cmdb/cert/server.key
  keyFile:
  # CA证书的路径，用于验证对方证书,,如:/data/cmdb/cert/ca.crt
  caFile:
  # 用于解密根据RFC1423加密的证书密钥的PEM块
  password:

# 调用apigw接口相关配置
apiGW:
  bkGseApiGatewayUrl: __BK_API_GATEWAY_GSE_URL__
  bkNoticeApiGatewayUrl: __BK_API_GATEWAY_BK_NOTICE_URL__
  bkCmdbApiGatewayUrl: __BK_API_GATEWAY_CMDB_URL__
  appCode: __BK_CMDB_APP_CODE__
  appSecret: __BK_CMDB_APP_SECRET__
  username: admin
  tls:
    # 客户端是否验证服务端证书，包含证书链和主机名，bool值, true为不校验, false为校验
    insecureSkipVerify: true
    # 服务使用的证书的路径,如:/data/cmdb/cert/server.crt
    certFile:
    # 服务使用的证书对应的密钥的路径,如:/data/cmdb/cert/server.key
    keyFile:
    # CA证书的路径，用于验证对方证书,如:/data/cmdb/cert/ca.crt
    caFile:
    # 用于解密根据RFC1423加密的证书密钥的PEM块
    password:

redis:
  #公共redis配置信息,用于存取缓存，用户信息等数据
  host: __BK_CMDB_REDIS_SENTINEL_HOST__:__BK_CMDB_REDIS_SENTINEL_PORT__
  pwd: __BK_CMDB_REDIS_PASSWORD__
  sentinelPwd: __BK_CMDB_REDIS_SENTINEL_PASSWORD__
  database: "0"
  maxOpenConns: 3000
  maxIDleConns: 1000
  masterName: __BK_CMDB_REDIS_MASTER_NAME__

mongodb:
  host: __BK_CMDB_MONGODB_HOST__
  port: __BK_CMDB_MONGODB_PORT__
  usr: __BK_CMDB_MONGODB_USERNAME__
  pwd: __BK_CMDB_MONGODB_PASSWORD__
  database: cmdb
  maxOpenConns: 3000
  maxIdleConns: 100
  mechanism: SCRAM-SHA-1
  rsName: rs0
  #mongo的socket连接的超时时间，以秒为单位，默认10s，最小5s，最大30s。
  socketTimeoutSeconds: 10